image: docker:19.03.8

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

before_script:
  - docker info

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: demo-ci
  CI_PROJECT_NAME: demo-ci
  REGISTRY_SERVER: sally

stages:
  - prepare
  - deploy

code-check:
  stage: prepare
  variables:
    POSTGRES_DB: db_test
    POSTGRES_USER: super
    POSTGRES_PASSWORD: creator_password
    RAILS_ENV: test
    HEROKU_DB_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB?pool=5
  services:
    - postgres:10
  script:
    - bundle exec rake test

production:
  stage: deploy
  only:
    - master
  when: manual
  dependencies:
    - code-check
  script:
    - IMAGE_VERSION=`TZ=UTC-8 date +%Y%m%d_%H%M%S`
    - echo ${CI_PROJECT_NAME}:$IMAGE_VERSION
    - touch docker_image_version
    - echo $IMAGE_VERSION > $CI_PROJECT_DIR/docker_image_version
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/senbaisang/demo-ci .
    - docker push registry.gitlab.com/senbaisang/demo-ci
    - docker run -d -p 3000:3000 --name demo-ci registry.gitlab.com/senbaisang/demo-ci

