image: ruby:2.6

before_script:
  - gem install bundle
  - bundle install

stages:
  - prepare

code-check:
  stage: prepare
  variables:
    POSTGRES_DB: db_test
    POSTGRES_USER: super
    POSTGRES_PASSWORD: creator_password
    RAILS_ENV: test
    HEROKU_DB_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB?pool=5
  services:
    - postgres:10
  script:
    - bundle exec rake test

