name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1
    - name: Install dependenties
      run: bundle install
    - name: Run tests
      run: bundle exec rake

