name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1
    - name: Install dependenties
      run: bundle install
    - name: Run tests
      run: bundle exec rake
    - name: Deploy to heroku
      run: git push heroku HEAD:master -f
